---
- name: Add or remove user account
  user:
    name: "{{ item.name }}"
    group: users
    home: /home/{{ item.name }}
    password: changeme
    state: "{{ user_state }}"
  with_items:
    - "{{ users }}"
  tags:
    - users

- name: Force user with default password to change password at next login
  command: chage -d 0 {{ item.name }}
  when: user_state == "present"
  with_items:
    - "{{ users }}"
  tags:
    - users

- name: Add or remove yum packages
  package:
    name: "{{ item }}"
    state: "{{ package_state }}"
    use: yum
  with_items:
    - "{{ package_list }}"
  tags:
    - packages

- name: Update user's password
  user:
    name: "{{ item.name }}"
    password: "{{ new_passwd }}"
    update_password: always
  with_items:
    - "{{ passwd_users }}"
  tags:
    - password

- name: install a new /etc/resolv.conf file
  template:
    src: resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - dns
