:badges:
:icons:
:toc2: left
:iconsdir: http://people.redhat.com/~jduncan/images/icons
:imagesdir: http://people.redhat.com/~jduncan/images
:date: 08-Aug-2016
:location: New York, NY

= Automation for Everyone
{location} : {date}

== Before We Get Started

=== Overview

Today is meant for anyone who has any exposure to Ansible, whether you have used it or not. We are going to start with a short overview (yes, slideware) and then we'll get into the lab as soon as possible. That is where we will spend most of our time.

=== Your Responsibilities

* Have a discussion. This will be boring if it's just us up here talking for over 2 hours.
* Participate. We are going to cut you loose in a live Ansible Tower instance here in just a little while.

=== Getting Up and going

There is always housekeeping, and we hope you're enjoying breakfast.

==== Your Laptop is Your Friend
Hopefully you have your laptop with you. If not, please find a shoulder-surfing buddy. See? Not only can we dig into Ansible but you can make a new friend!

[IMPORTANT]
.WiFi Access
====
ssid: `Red Hat Guest`

password: `atomic2016`
====

== Today's Team

=== Tyler Cross
Ansible Solutions Architect

=== Jamie Duncan
Cloud Solutions Architect, Public Sector

=== Bill Hirsch
Solutions Architect, Public Sector

== The Tower UI

=== Settings
