---
- name: ensure pip is installed
  package: name=python-pip state=present use=yum

- name: install tower-cli
  pip: name=ansible-tower-cli

- name: disable ssl for tower-cli for the demo
  command: tower-cli config verify_ssl false

- name: config username for ansible tower-cli
  command: tower-cli config username {{ t_user }}

- name: config password for ansible tower-cli
  command: tower-cli config password {{ t_pass }}

- name: Add user to Ansible Tower
  command: tower-cli user create --username {{ item.email }} --first-name {{ item.firstname }} --last-name {{ item.lastname }} --email {{ item.email }} --password {{ default_password }}
  with_items: "{{ users }}"

- name: Associate user with Ansible Organization
  command: tower-cli organization associate --user {{ item.email }} --organization "{{ organization }}"
  with_items: "{{ users }}"

- name: Associate user with Ansible Team
  command: tower-cli team associate --user {{ item.email }} --team "{{ team }}"
  with_items: "{{ users }}"
