---
- name: ensure pip is installed
  package: name=python-pip state=present

- name: install tower-cli
  pip: name=ansible-tower-cli

- name: config username for ansible tower-cli
  command: tower-cli config username {{ t_user }}

- name: config password for ansible tower-cli
  command: tower-cli config password {{ t_pass }}

- name: Add user to Ansible Tower
  command: tower-cli user create -h {{ t_host }} --username {{ item.email }} --first-name {{ item.firstname }} --last-name {{ item.lastname }} --email {{ item.email }} --password {{ default_password }}
  with_items: "{{ users }}"

- name: Associate user with Ansible Organization
  command: tower-cli organization associate -h {{ t_host }} --user {{ item.email }} --organization {{ organization }}
  with_items: "{{ users }}"
