---
- name: create ec2 instance
  ec2:
    keypair: ansible-lab-instances
    type: t2.small
    image: ami-ca56b5aa
    region: us-west-2
    count: "{{ ec2_instance_count | int }}"
    group_id: sg-921030f4
    vpc_subnet_id: subnet-7f611a1b
    assign_public_ip: yes
    instance_tags:
      Name: "{{ tower_user_name }}-lab"
      ansible_lab: true
      user_id: "{{ tower_user_name }}"
    wait: true
  register: ec2
  tags:
    - provision

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
  delegate_to: localhost
  tags:
    - provision

- name: gather ec2 facts
  action: ec2_facts
  tags:
    - terminate

- name: terminate user instances
  ec2:
    state: absent
    region: "{{ ec2_region }}"
    instance_ids: "{{ ansible_ec2_instance_id }}"
  tags:
    - terminate
