---
- name: create ec2 instance
  ec2:
    keypair: "{{ ec2_keypair }}"
    type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    count: "{{ ec2_instance_count }}"
    group_id: "{{ec2_security_group}}"
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    assign_public_ip: yes
    instance_tags:
      ansible_lab_user: True
      user_id: "{{ user_tag }}"
    wait: true
  register: ec2
  tags:
    - provision

- name: Wait for SSH to come up
  local_action: wait_for host={{ item.public_dns_name }} port=22 delay=60 timeout={{ aws_timeout }} state=started
  with_items: "{{ ec2.instances }}"
  tags:
    - provision

- name: terminate user instances
  ec2:
    state: terminated
    instance_tags:
      user_id: "{{ user_tag }}"
  tags:
    - terminate

- name: terminate all lab instances
  ec2:
    instance_tags:
      ansible_lab_user: True
    state: terminated
  tags:
    - terminate_all
