- name: suspend source VM
  command: /usr/bin/virsh suspend {{source_vm}}

- name: Use virt-clone to clone existing vm
  command: /usr/bin/virt-clone --connect {{connect}} --original {{source_vm}} --name {{target_vm}} --file {{path}}

- name: resume source VM
  command: /usr/bin/virsh resume {{source_vm}}

- name: start new VM
  command: /usr/bin/virsh start {{target_vm}}
