---
- name: ensure pip is installed
  package: name=python-pip state=present use=yum
  tags:
    - common

- name: install tower-cli
  pip: name=ansible-tower-cli
  tags:
    - common

- name: disable ssl for tower-cli for the demo
  command: tower-cli config verify_ssl false
  tags:
    - common

- name: config username for ansible tower-cli
  command: tower-cli config username {{ t_user }}
  tags:
    - common

- name: config password for ansible tower-cli
  command: tower-cli config password {{ t_pass }}
  tags:
    - common

- name: Add user to Ansible Tower
  command: tower-cli user create --username {{ item.email }} --first-name {{ item.firstname }} --last-name {{ item.lastname }} --email {{ item.email }} --password {{ default_password }}
  with_items: "{{ users }}"
  tags:
    - users

- name: Associate user with Ansible Organization
  command: tower-cli organization associate --user {{ item.email }} --organization "{{ organization }}"
  with_items: "{{ users }}"
  tags:
    - users

- name: Associate user with Ansible Team
  command: tower-cli team associate --user {{ item.email }} --team "{{ team }}"
  with_items: "{{ users }}"
  tags:
    - users

- name: Create Tower Organization
  command: tower-cli organization create --name {{org_name}} --description {{org_desc}}
  tags:
    - setup

- name: Create Tower Team
  command: tower-cli team create --name {{team_name}} --description {{team_desc}}
  tags:
    - setup

- name: Create Slack Notifiction template
  command: tower-cli notification_template create --name {{notification_name}} --description {{notification_desc}} --notification-type slack --channels {{slack_channels}} --token {{slack_token}}
  tags:
    - setup
